### ISSUE TITLE
Client doesn't allow to perform client_credentials flow

### ISSUE THREAD

**Issue by lukaszozimek** [ory/hydra-client-go#1]
Hi,

I've got a problem with the client library, because I don't see the option to perform client_credentials flow:
```
/oauth2/token POST
payload
grant_type:client_credentials
client_id:micro-service-client
client_secret:micro-service-secre

```
Could you tell me is it possible somehow to do this with the current client version?
If not I am happy to contribute to this project and provide the implementation.

**Comment by aeneasr** [comment]
Thank you for opening this issue. Unfortunately, the auto-generated client doesn't work well with OAuth2 so please use another library to perform OAuth2 flows - we have documented this also here: https://www.ory.sh/docs/hydra/sdk/go#configuration

> Be aware that endpoints /oauth2/auth and /oauth2/token MUST NOT be consumed using this SDK. Use golang.org/x/oauth2 instead.

Hope this helps

**Comment by lukaszozimek** [comment]
Thank you so much for the clarification.
I am closing ticket
