### ISSUE TITLE
Accept Consent request session model incorrect

### ISSUE THREAD

**Issue by matejkramny** [ory/hydra-client-go#10]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-client-go/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-client-go/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The model for the accept consent session request seems incorrect -

https://github.com/ory/hydra-client-go/blob/master/model_consent_request_session.go#L23

It's type `"idToken": map[string]map[string]interface{}` when the API docs suggest it is `"idToken": map[string]interface{}`

The JS (node) api also sends an object of key: string, value: any. The dart api also has a similar mapping, but of String: JSONObject.

I can't find any suitable examples of what the body should be..

is this correct?
```
idToken: {
  email: { email: "hello@email.com" },
  name: { name: "foo bar" },
}
```

The openapi consumer crashes

### Reproducing the bug

Create a login session/ consent

### Version

1.11.7

### In which environment are you deploying?

Kubernetes

**Comment by aeneasr** [comment]
Thank you for the report! This needs to be fixed in Ory Hydra‘s code base where we extract the info for API Specs :)

**Comment by matejkramny** [comment]
Haha, thanks i'll submit there. Cheers
