### ISSUE TITLE
Accept Consent Not Working

### ISSUE THREAD

**Issue by alusicode** [ory/hydra-client-go#2]
i am trying to accept consent request but i keep. getting the following error

```go
resp, err :=  worker.Admin.AcceptConsentRequest(&admin.AcceptConsentRequestParams{
		 Body:             &models.AcceptConsentRequest{
			 GrantScope:               scopes,
			 Remember:                 remember,
		 },
		 ConsentChallenge: challenge,
		 Context:          ctx,

	 })

```

it fails with the following response..
**response status code does not match any response statuses defined for this endpoint in the swagger spec (status 400): {}**

in hydra logs i get 

`level=error msg="An error occurred while handling a request" code=400 debug= details="map[]" error="json: unknown field \"handled_at\"" reason= request-id= status=`

i updated hydra and now the error says

**ERROR: column "handled_at" of relation "hydra_oauth2_consent_request_handled" does not exist (SQLSTATE 42703) StatusCode:500}
exit status 1**

**Comment by aeneasr** [comment]
Looks like you're missing the proper SQL Migrations. I would recommend start with a fresh system and retrying based on the documentation. The errors stated do not actually have to do anything with the SDK, so I'll be closing this.
