### ISSUE TITLE
What is JSONRawMessage type?

### ISSUE THREAD

**Issue by karelbilek** [ory/hydra-client-go#3]
I want to use this repo

I don't know how to deal with JSONRawMessage type. The code in the model is

```
// JSONRawMessage JSONRawMessage represents a json.RawMessage that works well with JSON, SQL, and Swagger.
//
// swagger:model JSONRawMessage
type JSONRawMessage interface{}
```

What is actually there? Can I be sure that there is `json.RawMessage` in the interface? Why not use that instead of empty interface?

**Comment by karelbilek** [comment]
I see the documentation is from `sqlxx.JSONRawMessage`, which uses json.RawMessage as underlying type

but not sure what I get here in this code

**Comment by aeneasr** [comment]
That's just how OpenAPI generator currently works unfortunately. It might improve as we move to a new pipeline but for now we can't really change this, sorry!

**Comment by karelbilek** [comment]
that's OK. But what exactly is stored in the interface?

**Comment by aeneasr** [comment]
An arbitrary JSON string, e.g. `[]`, `{"foo":true}`, `null`, ...

**Comment by karelbilek** [comment]
so it is a string, not `json.RawMessage`? Thx.

**Comment by aeneasr** [comment]
No, it is the result of this: https://golang.org/pkg/encoding/json/#Unmarshal

**Comment by karelbilek** [comment]
That makes me even more confused :D that has `error` as result and `[]byte, interface{}` as parameters.

I will actually try that though instead of talking here
