### ISSUE TITLE
Introspect Handler throws 200 when mysql is down

### ISSUE THREAD

**Issue by aniketverma-zomato** [ory/hydra-client-go#8]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-client-go/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-client-go/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

We use IntrospectOAuth2Token HydraAdmin API to validate our access token. We fetch the user details from the token. We use MySQL with hydra client. Whenever due to failover or connections limit gets exceeded or any other MySQL Downtime error IntrospectOAuth2Token returns a nonerror state with an empty struct for a correct token.  So our system understands that it is an invalid token and our system logs the user out.  Instead of this we need an error state so that we can show an error state to the end user.,

### Reproducing the bug

1. Generate a valid access token.
2. Manually kill Mysql while the application is still running.
3. Call IntrospectOAuth2Token with the valid token generated in step 1.
4. Response does not contain any error state. Although we see in debug logs that there has been a fatal on MySql.

### Relevant log output

```shell
Below is the response when mysql is down and we call IntrospectOAuth2Token with a correct token.

[POST /oauth2/introspect][200] introspectOAuth2TokenOK  &{Active:0xc0000a6430 Aud:[] ClientID: Exp:0 Ext:<nil> Iat:0 Iss: Nbf:0 ObfuscatedSubject: Scope: Sub: TokenType: TokenUse: Username:}"
```

### Version

github.com/ory/hydra-client-go v1.9.2

### On which operating system are you observing this issue?

Other

### In which environment are you deploying?

Docker

**Comment by aeneasr** [comment]
You need to check wether `active` is set to true or false. If it is false, the token is invalid (for whatever reason). This is according to the OAuth2 specification.

**Comment by aniketverma-zomato** [comment]
@aeneasr if mysql server is down even for 30 secs all my end users would end up getting logged out. Ideally something went wrong message should be shown to the end user for 30 secs post that after retry experience would be back to normal.

**Comment by aeneasr** [comment]
I understand, that is indeed not ideal. The introspection spec is defined here: https://datatracker.ietf.org/doc/html/rfc7662#section-2.3

It currently doesn't give leeway for 500 errors or do you see it differently?
