### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by aimichelle** [ory/hydra-client-go#9]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-client-go/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-client-go/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

It looks like the LICENSE file was removed (along with other useful resources such as the contributing guide/code of conduct) in this commit: https://github.com/ory/hydra-client-go/commit/a98bdcd048644468cfd0bd77bb9986e958967011 

### Reproducing the bug

Git checkout the repo, check the LICENSE is not available in the main branch.

### Version

n/a

**Comment by rohansingh** [comment]
@aeneasr Was this by design? The problem is larger than just the LICENSE file, looks like the whole repo now is somewhat broken and doesn't match the documentation at: https://www.ory.sh/docs/hydra/sdk/go

It's unclear how to use the client any more.

**Comment by aeneasr** [comment]
The license is the one from OpenAPI Generator (I believe Apache 2). We will soon add license files to the autogenerated repos.

Regarding your question please see https://github.com/ory/sdk/issues/152#issuecomment-1046731486

**Comment by aeneasr** [comment]
This is fixed
